---

- name: Airflow | Check users (> 2.0)
  become: true
  become_user: "{{ airflow_user }}"
  command: "{{ airflow_executable }} users list"
  register: airflow_check_users
  changed_when: false
  when: airflow_version is version( '2.0.0', '>=')

- name: Airflow | Create Admin users (> 2.0)
  become: true
  become_user: "{{ airflow_user }}"
  command: "{{ airflow_executable }} users create --username {{ item.username }} --password {{ item.password }} --firstname {{ item.firstname }} --lastname {{ item.lastname }} --role {{ item.role }} --email {{ item.email }}"
  with_items: "{{ airflow_admin_users }}"
  when:
    - airflow_version is version( '2.0.0', '>=')
  register: create_admin_users_airflow2
  failed_when: "'FAILED' in create_admin_users_airflow2.stderr"

- name: Airflow | Create regular users (> 2.0)
  become: true
  become_user: "{{ airflow_user }}"
  command:
    argv:
      - "{{ airflow_executable }}"
      - users
      - create
      - --username
      - "{{ item.username }}"
      - --password
      - "{{ item.password }}"
      - --firstname
      - "{{ item.firstname }}"
      - --lastname
      - "{{ item.lastname }}"
      - --role
      - "{{ item.role }}"
      - --email
      - "{{ item.email }}"
  no_log: true
  with_items: "{{ airflow_regular_users }}"
  when:
    - airflow_version is version( '2.0.0', '>=')
    - airflow_regular_users is defined
    - "item.email not in airflow_check_users.stdout"
